version: '3.8'
services:
  postgres:
    image: postgres:13.3
    container_name: auth_postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-auth_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

volumes:
  postgres_data: